import random

# User has to guess a number generated by the computer


def guessing_function():
    """
    A function that generates a random number and upon
    user input guesses, generates an automatic response. 
    Ends when the user correctly guesses the number.

    """

    random_number_100 = random.randint(1, 101)

    user_guess = int(input("Guess an integer between 1 and 100: "))

    
    while random_number_100 != user_guess:

        if user_guess > 100 or user_guess < 1:
            print(f"You can't choose {user_guess}\n")
            print("Please pick an integer between 1 and 100 only!")
            pass
            user_guess = int(input("Guess an integer between 1 and 100: "))
    
        elif user_guess > random_number_100:
            print("Too high, try a bit lower!")
            user_guess = int(input("Guess an integer between 1 and 100: "))
        elif user_guess < random_number_100:
            print("Too low, try a bit higher!")
            user_guess = int(input("Guess an integer between 1 and 100: "))
        
    print(f"You got it! The number was: {random_number_100}")

guessing_function()


# Computer has to guess a number generated by the User



# Coin Toss (Heads/Tails)